{"time":"2024-09-02 13:24:59","level":"INFO","module":"__init__","method":"setup","line":484,"path":"\/Users\/alanchaung\/opt\/anaconda3\/lib\/python3.9\/site-packages\/anaconda_navigator\/widgets\/main_window\/__init__.py","message":"Initial setup"}
{"time":"2024-09-02 13:33:08","level":"INFO","module":"__init__","method":"setup","line":500,"path":"\/Users\/alanchaung\/opt\/anaconda3\/lib\/python3.9\/site-packages\/anaconda_navigator\/widgets\/main_window\/__init__.py","message":"Normal setup"}
{"time":"2024-09-02 14:08:13","level":"INFO","module":"__init__","method":"setup","line":484,"path":"\/Users\/alanchaung\/opt\/anaconda3\/lib\/python3.9\/site-packages\/anaconda_navigator\/widgets\/main_window\/__init__.py","message":"Initial setup"}
{"time":"2024-09-02 15:32:35","level":"INFO","module":"__init__","method":"setup","line":484,"path":"\/Users\/alanchaung\/opt\/anaconda3\/lib\/python3.9\/site-packages\/anaconda_navigator\/widgets\/main_window\/__init__.py","message":"Initial setup"}
{"time":"2024-09-02 15:44:27","level":"INFO","module":"__init__","method":"setup","line":500,"path":"\/Users\/alanchaung\/opt\/anaconda3\/lib\/python3.9\/site-packages\/anaconda_navigator\/widgets\/main_window\/__init__.py","message":"Normal setup"}
{"time":"2024-09-02 15:45:17","level":"INFO","module":"__init__","method":"setup","line":500,"path":"\/Users\/alanchaung\/opt\/anaconda3\/lib\/python3.9\/site-packages\/anaconda_navigator\/widgets\/main_window\/__init__.py","message":"Normal setup"}
{"time":"2024-09-02 15:45:33","level":"INFO","module":"__init__","method":"setup","line":500,"path":"\/Users\/alanchaung\/opt\/anaconda3\/lib\/python3.9\/site-packages\/anaconda_navigator\/widgets\/main_window\/__init__.py","message":"Normal setup"}
{"time":"2024-09-02 15:46:00","level":"INFO","module":"__init__","method":"setup","line":500,"path":"\/Users\/alanchaung\/opt\/anaconda3\/lib\/python3.9\/site-packages\/anaconda_navigator\/widgets\/main_window\/__init__.py","message":"Normal setup"}
{"time":"2024-09-02 15:46:26","level":"INFO","module":"__init__","method":"setup","line":500,"path":"\/Users\/alanchaung\/opt\/anaconda3\/lib\/python3.9\/site-packages\/anaconda_navigator\/widgets\/main_window\/__init__.py","message":"Normal setup"}
{"time":"2024-09-02 15:48:11","level":"INFO","module":"__init__","method":"setup","line":500,"path":"\/Users\/alanchaung\/opt\/anaconda3\/lib\/python3.9\/site-packages\/anaconda_navigator\/widgets\/main_window\/__init__.py","message":"Normal setup"}
{"time":"2024-09-02 15:48:18","level":"INFO","module":"__init__","method":"setup","line":500,"path":"\/Users\/alanchaung\/opt\/anaconda3\/lib\/python3.9\/site-packages\/anaconda_navigator\/widgets\/main_window\/__init__.py","message":"Normal setup"}
{"time":"2024-09-02 15:49:30","level":"WARNING","module":"conda_api","method":"communicate","line":320,"path":"\/Users\/alanchaung\/opt\/anaconda3\/lib\/python3.9\/site-packages\/anaconda_navigator\/api\/conda_api.py","message":"Problem parsing conda json output. Line 0. Data - \n\nUpdating pandas is constricted by \n\nanaconda -> requires pandas==1.4.2=py39he9d5cce_0\n\nIf you are sure you want an update of your package either try `conda update --all` or install a specific version of the package you want using `conda install <pkg>=<version>`\n\n{\n  \"actions\": {\n    \"FETCH\": [\n      {\n        \"arch\": null,\n        \"build\": \"py39hecd8cb5_0\",\n        \"build_number\": 0,\n        \"channel\": \"https:\/\/repo.anaconda.com\/pkgs\/main\/osx-64\",\n        \"constrains\": [],\n        \"depends\": [\n          \"python >=3.9,<3.10.0a0\",\n          \"setuptools\"\n        ],\n        \"fn\": \"conda-pack-0.7.1-py39hecd8cb5_0.conda\",\n        \"legacy_bz2_md5\": \"ab9e354cc91207579ef3cb26ce85e963\",\n        \"license\": \"BSD-3-Clause\",\n        \"license_family\": \"BSD\",\n        \"md5\": \"2220bd05cac79392ffebc8e00c1e3f47\",\n        \"name\": \"conda-pack\",\n        \"platform\": null,\n        \"sha256\": \"0dd7c8a8ee305b907cdb5682de109c5e58ee04422ff6fa6a5334457e0f4c47b3\",\n        \"size\": 52669,\n        \"subdir\": \"osx-64\",\n        \"timestamp\": 1710258113167,\n        \"url\": \"https:\/\/repo.anaconda.com\/pkgs\/main\/osx-64\/conda-pack-0.7.1-py39hecd8cb5_0.conda\",\n        \"version\": \"0.7.1\"\n      },\n      {\n        \"arch\": null,\n        \"build\": \"py39hecd8cb5_0\",\n        \"build_number\": 0,\n        \"channel\": \"https:\/\/repo.anaconda.com\/pkgs\/main\/osx-64\",\n        \"constrains\": [\n          \"cryptography >=3.4.0\"\n        ],\n        \"depends\": [\n          \"python >=3.9,<3.10.0a0\"\n        ],\n        \"fn\": \"pyjwt-2.8.0-py39hecd8cb5_0.conda\",\n        \"legacy_bz2_md5\": \"d5174d56bd2a975adbd5f2650c401938\",\n        \"license\": \"MIT\",\n        \"license_family\": \"MIT\",\n        \"md5\": \"2d6665fe2d9d592f5dba29bf1cec201f\",\n        \"name\": \"pyjwt\",\n        \"platform\": null,\n        \"sha256\": \"188196fceb84d1f6fdbb8bfb0d7eced30c361f47beaed777f9822e398f87ffd5\",\n        \"size\": 76950,\n        \"subdir\": \"osx-64\",\n        \"timestamp\": 1715095200911,\n        \"url\": \"https:\/\/repo.anaconda.com\/pkgs\/main\/osx-64\/pyjwt-2.8.0-py39hecd8cb5_0.conda\",\n        \"version\": \"2.8.0\"\n      }\n    ],\n    \"LINK\": [\n      {\n        \"base_url\": \"https:\/\/repo.anaconda.com\/pkgs\/main\",\n        \"build_number\": 0,\n        \"build_string\": \"py39hecd8cb5_0\",\n        \"channel\": \"pkgs\/main\",\n        \"dist_name\": \"pyjwt-2.8.0-py39hecd8cb5_0\",\n        \"name\": \"pyjwt\",\n        \"platform\": \"osx-64\",\n        \"version\": \"2.8.0\"\n      },\n      {\n        \"base_url\": \"https:\/\/repo.anaconda.com\/pkgs\/main\",\n        \"build_number\": 0,\n        \"build_string\": \"py39hecd8cb5_0\",\n        \"channel\": \"pkgs\/main\",\n        \"dist_name\": \"conda-pack-0.7.1-py39hecd8cb5_0\",\n        \"name\": \"conda-pack\",\n        \"platform\": \"osx-64\",\n        \"version\": \"0.7.1\"\n      }\n    ],\n    \"PREFIX\": \"\/Users\/alanchaung\/opt\/anaconda3\",\n    \"UNLINK\": [\n      {\n        \"base_url\": \"https:\/\/repo.anaconda.com\/pkgs\/main\",\n        \"build_number\": 0,\n        \"build_string\": \"pyhd3eb1b0_0\",\n        \"channel\": \"pkgs\/main\",\n        \"dist_name\": \"conda-pack-0.6.0-pyhd3eb1b0_0\",\n        \"name\": \"conda-pack\",\n        \"platform\": \"noarch\",\n        \"version\": \"0.6.0\"\n      },\n      {\n        \"base_url\": \"https:\/\/repo.anaconda.com\/pkgs\/main\",\n        \"build_number\": 0,\n        \"build_string\": \"py39hecd8cb5_0\",\n        \"channel\": \"pkgs\/main\",\n        \"dist_name\": \"pyjwt-2.1.0-py39hecd8cb5_0\",\n        \"name\": \"pyjwt\",\n        \"platform\": \"osx-64\",\n        \"version\": \"2.1.0\"\n      }\n    ]\n  },\n  \"dry_run\": true,\n  \"prefix\": \"\/Users\/alanchaung\/opt\/anaconda3\",\n  \"success\": true\n}\n. Error - Expecting value: line 3 column 1 (char 2)"}
{"time":"2024-09-02 15:49:30","level":"WARNING","module":"conda_api","method":"communicate","line":320,"path":"\/Users\/alanchaung\/opt\/anaconda3\/lib\/python3.9\/site-packages\/anaconda_navigator\/api\/conda_api.py","message":"Problem parsing conda json output. Line 0. Data - \n\nUpdating pandas is constricted by \n\nanaconda -> requires pandas==1.4.2=py39he9d5cce_0\n\nIf you are sure you want an update of your package either try `conda update --all` or install a specific version of the package you want using `conda install <pkg>=<version>`\n\n{\n  \"actions\": {\n    \"FETCH\": [\n      {\n        \"arch\": null,\n        \"build\": \"py39hecd8cb5_0\",\n        \"build_number\": 0,\n        \"channel\": \"https:\/\/repo.anaconda.com\/pkgs\/main\/osx-64\",\n        \"constrains\": [],\n        \"depends\": [\n          \"python >=3.9,<3.10.0a0\",\n          \"setuptools\"\n        ],\n        \"fn\": \"conda-pack-0.7.1-py39hecd8cb5_0.conda\",\n        \"legacy_bz2_md5\": \"ab9e354cc91207579ef3cb26ce85e963\",\n        \"license\": \"BSD-3-Clause\",\n        \"license_family\": \"BSD\",\n        \"md5\": \"2220bd05cac79392ffebc8e00c1e3f47\",\n        \"name\": \"conda-pack\",\n        \"platform\": null,\n        \"sha256\": \"0dd7c8a8ee305b907cdb5682de109c5e58ee04422ff6fa6a5334457e0f4c47b3\",\n        \"size\": 52669,\n        \"subdir\": \"osx-64\",\n        \"timestamp\": 1710258113167,\n        \"url\": \"https:\/\/repo.anaconda.com\/pkgs\/main\/osx-64\/conda-pack-0.7.1-py39hecd8cb5_0.conda\",\n        \"version\": \"0.7.1\"\n      },\n      {\n        \"arch\": null,\n        \"build\": \"py39hecd8cb5_0\",\n        \"build_number\": 0,\n        \"channel\": \"https:\/\/repo.anaconda.com\/pkgs\/main\/osx-64\",\n        \"constrains\": [\n          \"cryptography >=3.4.0\"\n        ],\n        \"depends\": [\n          \"python >=3.9,<3.10.0a0\"\n        ],\n        \"fn\": \"pyjwt-2.8.0-py39hecd8cb5_0.conda\",\n        \"legacy_bz2_md5\": \"d5174d56bd2a975adbd5f2650c401938\",\n        \"license\": \"MIT\",\n        \"license_family\": \"MIT\",\n        \"md5\": \"2d6665fe2d9d592f5dba29bf1cec201f\",\n        \"name\": \"pyjwt\",\n        \"platform\": null,\n        \"sha256\": \"188196fceb84d1f6fdbb8bfb0d7eced30c361f47beaed777f9822e398f87ffd5\",\n        \"size\": 76950,\n        \"subdir\": \"osx-64\",\n        \"timestamp\": 1715095200911,\n        \"url\": \"https:\/\/repo.anaconda.com\/pkgs\/main\/osx-64\/pyjwt-2.8.0-py39hecd8cb5_0.conda\",\n        \"version\": \"2.8.0\"\n      }\n    ],\n    \"LINK\": [\n      {\n        \"base_url\": \"https:\/\/repo.anaconda.com\/pkgs\/main\",\n        \"build_number\": 0,\n        \"build_string\": \"py39hecd8cb5_0\",\n        \"channel\": \"pkgs\/main\",\n        \"dist_name\": \"pyjwt-2.8.0-py39hecd8cb5_0\",\n        \"name\": \"pyjwt\",\n        \"platform\": \"osx-64\",\n        \"version\": \"2.8.0\"\n      },\n      {\n        \"base_url\": \"https:\/\/repo.anaconda.com\/pkgs\/main\",\n        \"build_number\": 0,\n        \"build_string\": \"py39hecd8cb5_0\",\n        \"channel\": \"pkgs\/main\",\n        \"dist_name\": \"conda-pack-0.7.1-py39hecd8cb5_0\",\n        \"name\": \"conda-pack\",\n        \"platform\": \"osx-64\",\n        \"version\": \"0.7.1\"\n      }\n    ],\n    \"PREFIX\": \"\/Users\/alanchaung\/opt\/anaconda3\",\n    \"UNLINK\": [\n      {\n        \"base_url\": \"https:\/\/repo.anaconda.com\/pkgs\/main\",\n        \"build_number\": 0,\n        \"build_string\": \"pyhd3eb1b0_0\",\n        \"channel\": \"pkgs\/main\",\n        \"dist_name\": \"conda-pack-0.6.0-pyhd3eb1b0_0\",\n        \"name\": \"conda-pack\",\n        \"platform\": \"noarch\",\n        \"version\": \"0.6.0\"\n      },\n      {\n        \"base_url\": \"https:\/\/repo.anaconda.com\/pkgs\/main\",\n        \"build_number\": 0,\n        \"build_string\": \"py39hecd8cb5_0\",\n        \"channel\": \"pkgs\/main\",\n        \"dist_name\": \"pyjwt-2.1.0-py39hecd8cb5_0\",\n        \"name\": \"pyjwt\",\n        \"platform\": \"osx-64\",\n        \"version\": \"2.1.0\"\n      }\n    ]\n  },\n  \"dry_run\": true,\n  \"prefix\": \"\/Users\/alanchaung\/opt\/anaconda3\",\n  \"success\": true\n}\n. Error - Expecting value: line 3 column 1 (char 2)"}
{"time":"2024-09-02 15:49:53","level":"INFO","module":"__init__","method":"setup","line":500,"path":"\/Users\/alanchaung\/opt\/anaconda3\/lib\/python3.9\/site-packages\/anaconda_navigator\/widgets\/main_window\/__init__.py","message":"Normal setup"}
{"time":"2024-09-02 15:52:45","level":"INFO","module":"__init__","method":"setup","line":500,"path":"\/Users\/alanchaung\/opt\/anaconda3\/lib\/python3.9\/site-packages\/anaconda_navigator\/widgets\/main_window\/__init__.py","message":"Normal setup"}
{"time":"2024-09-02 15:53:08","level":"INFO","module":"__init__","method":"setup","line":500,"path":"\/Users\/alanchaung\/opt\/anaconda3\/lib\/python3.9\/site-packages\/anaconda_navigator\/widgets\/main_window\/__init__.py","message":"Normal setup"}
{"time":"2024-09-02 15:57:19","level":"ERROR","module":"__init__","method":"global_exception_logger","line":19,"path":"\/Users\/alanchaung\/opt\/anaconda3\/lib\/python3.9\/site-packages\/anaconda_navigator\/utils\/logs\/__init__.py","message":"'utf-8' codec can't decode byte 0xe1 in position 16200: invalid continuation byte","exception":"Traceback (most recent call last):\n  File \"\/Users\/alanchaung\/opt\/anaconda3\/lib\/python3.9\/site-packages\/anaconda_navigator\/api\/conda_api.py\", line 249, in _partial\n    stdout = handle_qbytearray(raw_stdout, self.get_encoding())\n  File \"\/Users\/alanchaung\/opt\/anaconda3\/lib\/python3.9\/site-packages\/anaconda_navigator\/api\/conda_api.py\", line 105, in handle_qbytearray\n    return to_text_string(obj, encoding=encoding)\n  File \"\/Users\/alanchaung\/opt\/anaconda3\/lib\/python3.9\/site-packages\/anaconda_navigator\/api\/conda_api.py\", line 98, in to_text_string\n    return str(obj, encoding)\nUnicodeDecodeError: 'utf-8' codec can't decode byte 0xe1 in position 16200: invalid continuation byte"}
{"time":"2024-09-02 15:57:19","level":"ERROR","module":"__init__","method":"global_exception_logger","line":19,"path":"\/Users\/alanchaung\/opt\/anaconda3\/lib\/python3.9\/site-packages\/anaconda_navigator\/utils\/logs\/__init__.py","message":"'utf-8' codec can't decode byte 0x80 in position 16199: invalid start byte","exception":"Traceback (most recent call last):\n  File \"\/Users\/alanchaung\/opt\/anaconda3\/lib\/python3.9\/site-packages\/anaconda_navigator\/api\/conda_api.py\", line 249, in _partial\n    stdout = handle_qbytearray(raw_stdout, self.get_encoding())\n  File \"\/Users\/alanchaung\/opt\/anaconda3\/lib\/python3.9\/site-packages\/anaconda_navigator\/api\/conda_api.py\", line 105, in handle_qbytearray\n    return to_text_string(obj, encoding=encoding)\n  File \"\/Users\/alanchaung\/opt\/anaconda3\/lib\/python3.9\/site-packages\/anaconda_navigator\/api\/conda_api.py\", line 98, in to_text_string\n    return str(obj, encoding)\nUnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 16199: invalid start byte"}
{"time":"2024-09-02 15:57:19","level":"ERROR","module":"__init__","method":"global_exception_logger","line":19,"path":"\/Users\/alanchaung\/opt\/anaconda3\/lib\/python3.9\/site-packages\/anaconda_navigator\/utils\/logs\/__init__.py","message":"'utf-8' codec can't decode byte 0xe0 in position 16203: invalid continuation byte","exception":"Traceback (most recent call last):\n  File \"\/Users\/alanchaung\/opt\/anaconda3\/lib\/python3.9\/site-packages\/anaconda_navigator\/api\/conda_api.py\", line 249, in _partial\n    stdout = handle_qbytearray(raw_stdout, self.get_encoding())\n  File \"\/Users\/alanchaung\/opt\/anaconda3\/lib\/python3.9\/site-packages\/anaconda_navigator\/api\/conda_api.py\", line 105, in handle_qbytearray\n    return to_text_string(obj, encoding=encoding)\n  File \"\/Users\/alanchaung\/opt\/anaconda3\/lib\/python3.9\/site-packages\/anaconda_navigator\/api\/conda_api.py\", line 98, in to_text_string\n    return str(obj, encoding)\nUnicodeDecodeError: 'utf-8' codec can't decode byte 0xe0 in position 16203: invalid continuation byte"}
{"time":"2024-09-02 15:57:45","level":"INFO","module":"__init__","method":"setup","line":500,"path":"\/Users\/alanchaung\/opt\/anaconda3\/lib\/python3.9\/site-packages\/anaconda_navigator\/widgets\/main_window\/__init__.py","message":"Normal setup"}
{"time":"2024-09-02 16:07:35","level":"INFO","module":"__init__","method":"setup","line":500,"path":"\/Users\/alanchaung\/opt\/anaconda3\/lib\/python3.9\/site-packages\/anaconda_navigator\/widgets\/main_window\/__init__.py","message":"Normal setup"}
{"time":"2024-09-02 16:23:00","level":"INFO","module":"__init__","method":"setup","line":500,"path":"\/Users\/alanchaung\/opt\/anaconda3\/lib\/python3.9\/site-packages\/anaconda_navigator\/widgets\/main_window\/__init__.py","message":"Normal setup"}
{"time":"2024-09-02 16:23:09","level":"INFO","module":"__init__","method":"setup","line":500,"path":"\/Users\/alanchaung\/opt\/anaconda3\/lib\/python3.9\/site-packages\/anaconda_navigator\/widgets\/main_window\/__init__.py","message":"Normal setup"}
{"time":"2024-09-03 11:47:42","level":"INFO","module":"__init__","method":"setup","line":484,"path":"\/Users\/alanchaung\/opt\/anaconda3\/lib\/python3.9\/site-packages\/anaconda_navigator\/widgets\/main_window\/__init__.py","message":"Initial setup"}
{"time":"2024-09-03 11:57:17","level":"INFO","module":"__init__","method":"setup","line":484,"path":"\/Users\/alanchaung\/opt\/anaconda3\/lib\/python3.9\/site-packages\/anaconda_navigator\/widgets\/main_window\/__init__.py","message":"Initial setup"}
{"time":"2024-09-04 16:17:15","level":"INFO","module":"__init__","method":"setup","line":484,"path":"\/Users\/alanchaung\/opt\/anaconda3\/lib\/python3.9\/site-packages\/anaconda_navigator\/widgets\/main_window\/__init__.py","message":"Initial setup"}
{"time":"2024-09-04 17:14:16","level":"INFO","module":"__init__","method":"setup","line":484,"path":"\/Users\/alanchaung\/opt\/anaconda3\/lib\/python3.9\/site-packages\/anaconda_navigator\/widgets\/main_window\/__init__.py","message":"Initial setup"}
